# **Methodological Guide**

In this chapter the plugin involving computations and statistical methods are described.
The R code for each plugin can be downloaded from the SWS and the shiny can be provided by the IT.
R scripts are commented so to ease the reading by an external programmer.


## Outlier detection (Plugin: pp_OutlierDetection) {#pp_OutlierDetection}

After the data have been transferred from the Questionnaire to the Preparation dataset, and the data have been revised up to available year _t-1_ (being _t_ the last year available in the questionnaire) the outlier detection runs for the last available year _t_. The plugin **pp_OutlierDetection** identifies the outlier of the last questionnaire year applying three different methods: interquartile range (IQR) on the price level, interquartile range (IQR) on price variation, built-in in R function that applies the _supsmu_ method.

1. interquartile range (IQR) method on the price level: let **Q1** and **Q3** be the value corresponding respectively to the first and third quartile of the price series, the IQR method identifies as outlier all values lower than **Q1 - 1.5x(Q3-Q1)** or higher than **Q3 + 1.5x(Q3-Q1)**.

2. interquartile range (IQR) method on price variation: the same mehtod of point 1 is applied but now the price variation series is considered.

3. ‘tsclean’ function built-in in R that applies the _supsmu_ method, i.e. the Friedman's ‘super smoother’, a running lines smoother which chooses between three spans for the lines. The running lines smoothers are symmetric, with k/2data points each side of the predicted point, and values of k as 0.5 * n, 0.2 * n and 0.05 * n, where n is the number of data points. If span is specified, a single smoother with span span * n is used. The best of the three smoothers is chosen by cross-validation for each prediction. The best spans are then smoothed by a running lines smoother and the final prediction chosen by linear interpolation. The FORTRAN code says: “For small samples (n < 40) or if there are substantial serial correlations between observations close in x-value, then a pre-specified fixed span smoother (span > 0) should be used. Reasonable span values are 0.2 to 0.4.” Cases with non-finite values are dropped.

For method 2 and 3, outlier detection is performed on the **SLC logarithmic series**, for method 1 the SLC price series is considered.
Identified outliers according to the three methods are compared. If two or all three method identified a point as outlier, this point is flagged as outlier (E;e) and can be reviewed in the shiny application before proceeding to the missing data imputation.
The flag of figures identified as outliers are saved into the **Annual Producer Prices (Preparation)** dataset.


## Methodology **Imputation plugin** (Plugin: PP_ImputationMethods)

After the outlier have been reviewed either for one or for all countries, the missing data imputation can be performed. The imputation of missing data first happens in the SWS via plugin and it is then assessed via shiny app.
The SWS plugin called 'PP_imputationMethods' estimate missing data according to up to six different methods and save the results in the 'imputation_annual_prices' datatable.

When the plugin runs, it considers SLC series and completes the series where the last questionnaire year is missing according to the following methodologies: ARIMAX, Ensemble approach, Linear model, Commodity group approach, Consumer Price Index (CPI) based approach and Price ratio approach.

The auxiliary variables used for these models are:

- Value added of Agriculture, Forestry and Fishing (logarithmic form, from SWS Macro indicator domain)

- Country GDP (logarithmic form, from SWS Macro indicator domain)

- GDP per capita

- Gross fixed capital formation of agriculture, forestry and fishing (from published Capital Stock domain in FAOSTAT)

- Yield, i.e. harvested production per unit of harvested area for crop products (from SWS Agriculture production dataset)

- Trade openness index (calculated by the ECO team and stored in the datatable 'toi_data')

- Price ratios (as per datatable 'pp_tcf')


All imputation is performed considering the logarithmic value of the price in SLC.
Results of the plugin, i.e. prices estimated according to the methods listed above are stored in the datatable 'imputation_annual_prices'. These values are presented in the shiny application so the user is not required to check upon the datatable itself.

The first method calculated by the plugin is the price ratio. If available, the reference price is multiplied by the price ratio to calculate the missing price.

After the price ratio method all other approaches are implemented inside a loop. 
The loop consider separately each country-commodity combination.

1. ARIMAX: The key feature of the ARIMAX approach is the presence of covariates. The choice of covariates is performed empirically by running ARIMAX models for all possible combinations and choosing the one with the minimum Akaike Information Criteria (AIC) value. Once the model is selected the forecast is performed on the series and the price imputed. The covariate are: GDP, value added of agriculture, forestry and fishing (both from the Macro Indicator domain), yield (from the Agriculture production dataset), Trade Openness Index (from the _toi_data_ datatable).

2. Linear model: it follows the same approach of the ARIMAX approach but uses a simple linear regression to estimate and impute the missing price.

3. Ensemble approach: the ensemble method builds a collection of simple models and combine them to obtain a composite model. Averaging multiple models the risk of choosing a poor model is reduced. The approach has two main steps: the building of the models and their combination. The model considered are: mean (mean of all observations), median (median of all observations), linear (linear regression), exponential (exponential function), logistic (logistic function), naive (linear interpolation followed by last observation carried forward and first observation carried backward), ARIMA (selected based on the corrected Akaike’s Information Criterion (AICC) and imputation via Kalman Filter), LOESS (local regression with linear models and model window varying based on sample size), splines(cubic spline interpolation), MARS (Multivariate Adaptive Regression Spline), mixed model (linear mixed model with time as a fixed effect and country as the random effect). All these models are then combined so that the final result is a weighted average of all the input models. This approach is completely automatized by the R function in the R package faoswsImputation. An extended presentation is available in the faoswsImputation package along with the function used to impute variable in the Git Hub repository SWS-Methodology.


4. Commodity group approach: starting from the CPC hierarchical classification, the higher level of the considered product is taken and all products belonging to this level are considered. The growth rate of each product is computed and the median of the group is calculated. The missing price value is then imputed applying the median growth rate to the latest available price. Depending on the availability of prices, the plugin consider two different level of the hierarchy.


5. Consumer Price Index (CPI) approach: CPI values are pulled from the SWS dataset 'consumer_price_indices'. If available, the food CPI is considered otherwise the general CPI is used. The growth rate is computed and applied to the latest price available to calculate the missing value.


6. Gross Domestic Price (GDP) approach: this approach considers either the value added of agriculture, forestry and fishing or the GDP if the previous is not available. As in previous approaches the growth rate is calculated and applied to the latest price available. Data used come from the 'Complete dataset' in the Macro Indicators domain.


All these possible imputation values are stored in the 'imputation_annual_prices' datatable and are displayed as possible values in the shiny application.


There is a second part of the plugin that performs interpolation. The interpolation is perfomed in case an official value has been collected through questionnaire or other publications in the latest year but the previous years had been imputed. To check if previous imputations were appropriate, values are re-calculated through interpolation and proposed to the user through the shiny app. 

Interpolation performed is linear, performed through a built-in R function _na.approx_. The interpolated values are saved in the 'interpolation_annual_prices' datatable and presented to the user in the shiny app.



## Producer Prices Indices (PPIs)

The FAO Agricultural Producer Price Indices measure annual changes in the selling prices received by farmers (prices at the farm-gate or at the first point of sale). The indices are constructed using price data in Standardised Local Currency (SLC).
The plugin Producer Price Indices (PPI) calculates the indices for each country for the:
- single item;
- item groups.

Single items are calculated by dividing the SLC price in the current year by the base year SLC price (e.g. average 2014-2016). The average price is calculated using estimated and official data, but not data specifically flagged not to disseminate.

$$PPI_{single item} = p / p_0$$

Where
p = current year price in SLC
$p_0$ = base year (average 2014-2016) price in SLC

For item groups, multiply current SLC price by base year (average 2014-2016) production quantity and by any group conversion factor for single items in each item group. Sum this and divide it by the sum of the single items’ base year (average 2014-2016) SLC price multiplied by the base year (average 2014-2016) production quantity and by any group conversion factor.

$$PPI_{group} = \sum(p * q_0 * Group factor) / \sum(p_0 * q_0 * Group factor)$$
over all single items in item group

Where
$q_0$ = base year (average 2014-2016) production quantity in MT
Group factor = for some item groups, such as Oilcrops primary, there is a conversion factor to use when aggregating.







## Purchasing Power Parities through the Geary-Khamis system

There are several aggregation methods used in international comparisons of GDP. One of the known approaches uses an international set of prices and purchasing power parities to compile comparable value aggregates. The method was developed by Geary and Khamis along with the Geary-Khamis equation system (GK). The system is used to compute the international dollar, a hypothetical unit of currency that has the same Purchasing Power Parity (PPP) that the U.S. dollar had in the United States of America at a given point. According to the study FAO (1993) and considering qij the quantity of ith commodity produced in jth country during a given period, pij the price of ith commodity in jth country in local currency, M the number of countries and N the number of commodities: 
‘_The GK method employs the repricing and PPP approaches concurrently, and is therefore based on the reference prices of commodities as well as the purchasing power parities. Suppose $PPP_j$ represents the parity of j-th currency with a numeraire currency, called international dollars. Then the international price $P_i$ is defined as an international average of prices of i-th commodity in different countries. As the price in different countries are expressed in respective national currencies, the GK-method uses national prices after conversion into a common currency using the PPPs. Thus the international price, $P_i$, of i-th commodity is defined as:

$$P_i = \sum_{j=1}^M (p_{ij}/PPP_j) \frac{q_{ij}}{ \sum_{j=1}^M q_{ij}} $$

This equation implies that the international price of i-th commodity is calculated by dividing the total value of output of i-th commodity across all countries, converted in international dollars, using PPPs, by the total quantity produced of i-th commodity. These prices cannot be computed unless the system specifies $PPP_j$ . The GK system defines the parity of j-th currency through the equation 2:

$$ PPP_j = \frac{ \sum_{i=1}^N p_{ij} q_{ij}}{\sum_{i=1}^N P_i q_{ij}} $$

The numerator of the equation represents the total value of output in j-th country expressed in national currency, and the denominator is the value of j-th country output evaluated by repricing at international prices $P_i$, in international dollars. Then $PPP_j$ gives the number of national currency units per international dollar. The Geary-Khamis system consists of equations 1 and 2, and requires the computation of the international prices Pi, and parities PPPj , which are defined using a system of simultaneous equations.’

### Iterative scheme
Specify any positive initial value for the parities, with $PPP_1 = 1$. In the absence of any additional information, an obvious choice is to set all the parities equal to unity, i.e. $PPP_1 = 1, PPP_2 = 1, . . . , PPP_M = 1$. These values are then substituted into the formula for the international prices $P_i$ in equation 1. Once these $P_i$’s are computed, they are in turn, used in equation 2 to compute the parities $PPP_j$ . After normalizing the computed parities and making $PPP_1 = 1$, these parities are compared with the initial values. If they are identical then the computation is terminated. Otherwise the computation proceeds by repeating the calculation using the new parities. These steps are repeated until the values converge. Convergence of the iterative procedure is guaranteed by the properties of the GK system discussed in Prasada Rao (1971) and Khamis (1972). Even in cases where $M$ and $N$ are very large, the procedure converges rapidly.’

